<script src="{{ asset('assets/auth/vendor/jquery/jquery-3.2.1.min.js') }}"></script>
<script src="{{ asset('assets/auth/vendor/animsition/js/animsition.min.js') }}"></script>
<script src="{{ asset('assets/auth/vendor/bootstrap/js/popper.js') }}"></script>
<script src="{{ asset('assets/auth/vendor/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/auth/vendor/select2/select2.min.js') }}"></script>
<script src="{{ asset('assets/auth/vendor/daterangepicker/moment.min.js') }}"></script>
<script src="{{ asset('assets/auth/vendor/daterangepicker/daterangepicker.js') }}"></script>
<script src="{{ asset('assets/auth/vendor/countdowntime/countdowntime.js') }}"></script>
<script src="{{ asset('assets/auth/js/custom.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
<script src="{{ asset('assets/auth/js/easyResponsiveTabs.js') }}"></script>
